language: cpp
cache: ccache
install:
    - git clone https://github.com/lammps/lammps lammps -b stable_12Dec2018 --depth=1
    - cp -r USER-PYFORCE/ lammps/src
script:
    - mkdir lammps/build && cd lammps/build
    - cmake ../cmake -D PKG_USER-PYFORCE=yes
    - make && make install
