on: push
name: Compile
jobs:
  build:
    name: docker://gcc:9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: "git clone https://github.com/lammps/lammps lammps -b stable_12Dec2018
          --depth=1 && cp -r USER-PYFORCE/ lammps/src && cd lammps/src && make yes-user-pyforce
          && make serial"
